#pragma once
//STD Headers

//Library Headers

//Void Engine Headers
#include "EngineMath/Vector.h"

namespace core {

	class Entity;

	/**
	 * Manifold is the struct generated by collision detection functions
	 * that destribes the nature of the detected collision
	 */
	struct Manifold {
		/**
		 * Constructor
		 */
		Manifold();

		/** First collider involved in collision */
		Entity* EntityA;
		
		/** Second collider involved in collision */
		Entity* EntityB;

		/** Distance the two objects are 
		 * intersecting along the CollisionNormal 
		 */
		float PenetrationDistance;

		/** Vector of resolution */
		math::Vector3 CollisionNormal;

	};

}

